### ISSUE TITLE
Add `settings-path` option support

### ISSUE THREAD

**Issue by sobolevn** [gforcada/flake8-isort#63]
There's an awesome setting for the `isort` that I use quite frequently in my setup: `settings-path`.
It allows to specify the desired configuration path.

Could I please add a support for this option to this library? 
I really miss it, and it won't interfere with nay other options.

That's how I think it should work:

0. If `--no-isort-config` is passed, then we ignore all other steps and use the default options 
0.1 We can also raise an exception if both `--no-isort-config` and `--isort-settings-path` are passed 
0.2 We can just ignore the `--isort-settings-path`
1. If this option is passed - then try to read this file. I have two options in case this file does not exist or can not be red:
1.1 We can raise an exception. All `flake8` check will fail with this exception. This will help to indicate about the problem early
1.2 Just fallback to the config finding behavior in case this file is missing
2. If no options are passed we should fallback to the config finding logic

@gforcada What do you think?

I personally prefer explicit exceptions. As they indicate about the problem. And not hiding it.

**Comment by gforcada** [comment]
@sobolevn hi!

Sorry for replying so late! :bowing_man: 

I'm ok on adding that option, though I would be great if we could get that from isort itself, would that be possible? :thinking: 

Anyway, with your current proposal:
- on ``0`` I would do ``0.2`` but rather than silently ignore it, log a warning explaining what happened and what will ``flake8-isort`` do: i.e. ``conflicting options are being used, fallback to try to find the config file on its own``
- on ``1`` I would do, again, a warning, the file could not be found, fallback to try to find the config file

Sounds reasonable? :thinking:

**Comment by GideonBear** [comment]
Hello @gforcada, is this planned? I can take a shot at implementing this

**Comment by gforcada** [comment]
@GideonBear not from my side, I would welcome a PR though 👍🏾

**Comment by GideonBear** [comment]
> @GideonBear not from my side, I would welcome a PR though 👍🏾

Alright, I'll take a look, thanks for the quick reply!
Can you assign me to the issue?

**Comment by gforcada** [comment]
@GideonBear there you are, let me know if you need help 😄

**Comment by GideonBear** [comment]
> @GideonBear there you are, let me know if you need help smile

Will do, thanks!

**Comment by GideonBear** [comment]
@gforcada The plugin is broken on master:
`TypeError: parse_options() missing 3 required positional arguments: 'option_manager', 'options', and 'args'`
It seems to be caused by 860e7c29f428c49e873b3aae701b44262005bf53.
Tests pass, but running flake8 with the plugin installed crashes, maybe it's a good idea to add a test to see if it doesn't crash?

**Comment by GideonBear** [comment]
The docs say:
```py
def parse_options(option_manager, options, args):
    pass
# or
def parse_options(options):
    pass
```

**Comment by gforcada** [comment]
Yes,, a test like that would be great, you are welcome to write it if you have the time and skills 👍🏾

**Comment by GideonBear** [comment]
@gforcada I don't even use `flake8-isort` anymore and will not be working on this. Can you unassign me?
Apologies for not working on this at the time, I don't remember why but I probably just forgot
