### PR TITLE
fix parse_options bug

### LINKED ISSUE #124: Breakage in 5.0.1
Using flake8 4.0.1:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 195, in provide_options
    parse_options(optmanager, options, extra_args)
TypeError: parse_options() missing 1 required positional argument: 'args'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 347, in initialize
    remaining_args,
  File "/usr/local/lib/python3.7/site-packages/flake8/main/application.py", line 200, in parse_configuration_and_cli
    self.option_manager, self.options, self.args
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 448, in provide_options
    list(self.manager.map(call_provide_options))
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 309, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 409, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/manager.py", line 197, in provide_options
    parse_options(options)
TypeError: parse_options() missing 3 required positional arguments: 'option_manager', 'options', and 'args'
```

### PR DESCRIPTION
**Pull request by casperdcl**
```python
TypeError: parse_options() missing 3 required positional arguments: 'option_manager', 'options', and 'args'
```

(e.g. [here](https://github.com/AMYPAD/CuVec/actions/runs/3500926406/jobs/5864067314#step:9:36))

- fixes #124
- caused by 860e7c2
  + see also https://github.com/gforcada/flake8-isort/issues/63#issuecomment-1318581190

### CODE REVIEW

**Review by mwgamble — APPROVED** [review]

**Comment by gforcada** [comment]
Thanks!! ✨

**Comment by gforcada** [comment]
`flake8-isort==5.0.2` is out 🔥

**Comment by casperdcl** [comment]
Didn't fix it unfortunately... https://github.com/AMYPAD/CuVec/actions/runs/3500926406/jobs/5865301779#step:9:50

Needs more testing 🙃

**Comment by casperdcl** [comment]
@gforcada I think these two need to be either `@class` or `@static` methods.

https://github.com/gforcada/flake8-isort/blob/7e03c82832d1d0904d02bc33d5f77eed6b1c7a3b/flake8_isort.py#L27-L37

**Comment by casperdcl** [comment]
Ok #127 is a manually tested working fix :)
